/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qodngnhmqbyoonhjtxmg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZG5nbmhtcWJ5b29uaGp0eG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTg5MjcsImV4cCI6MjA3NDUzNDkyN30.vXDWfLaCAZe5uNj-ZB3wrYS2tx6DGhO8updJI-JU_8A"